stages:
  - build
  - deploy

cache:
  paths:
    - _site/

jekyll:
  stage: build
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "en_US.UTF-8"
    LANGUAGE: "en_US.UTF-8"
  script:
    - gem install bundler
    - bundle install
    - jekyll build
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - _site/

s3-sync:
  stage: deploy
  image: nbering/docker-devops-tools:latest
  only:
    - master
  script:
    - cd _site
    - aws s3 sync . s3://nicholasbering.ca --delete --no-progress
