# Site settings
title: NicholasBering.ca
subtitle: "Programmer/Farmer"
email: nick@nicholasbering.ca
description: "Nicholas Bering is a self-taught software developer. He currently works for Back.io doing mostly front-end development for clients."
baseurl: ""
url: "http://nicholasbering.ca"
twitter_username: nickbering
github_username:  nbering

exclude:
    - .c9

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments

collections:
    resources:
        output: false
        categories:
            - "AngularJS Modules"
            - "Development Tools"
