# Site settings
title: Nicholas Bering
subtitle: "Canadian Software Developer"
email: nick@nicholasbering.ca
description: "Nicholas Bering is a self-taught software developer. He currently works for MedStack, dividing his time between cloud infrastructure, operations, and application development."
baseurl: ""
url: "https://nicholasbering.ca"
twitter_username: nickbering
github_username:  nbering
facebook_app_id: "1714325992123311"

exclude:
    - .c9
    - .gitlab-ci.yml
    - README.md
    - Gemfile
    - Gemfile.lock

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge

plugins:
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

collections:
    resources:
        output: false
    decks:
      output: true

defaults:
  - scope:
      path: ""
      type: "decks"
    values:
      layout: "reveal"
