# cSpell:words devcontainer markdownlint nickbering
# Site settings
title: Nicholas Bering
subtitle: "Canadian Software Developer"
email: nick@nicholasbering.ca
description: >
  Hi! I'm a Staff Engineer at MedStack, where I helped take a Cloud Platform for
  Healthcare from an idea, to a product with millions of dollars in annual
  revenue. This is my personal site.
baseurl: ""
url: "https://nicholasbering.ca"
twitter_username: nickbering
github_username:  nbering

exclude:
    - .c9
    - .gitlab-ci.yml
    - .ruby-lsp
    - .devcontainer
    - .markdownlint.json
    - .vscode
    - azure-pipelines.yml
    - README.md
    - Gemfile
    - Gemfile.lock

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge

collections:
    resources:
        output: false
    decks:
      output: true

defaults:
  - scope:
      path: ""
      type: "decks"
    values:
      layout: "reveal"
