# Site settings
title: balrog30.github.io
subtitle: "Programmer/Farmer"
email: nick@whitemeadowsfarms.com
description: "Nicholas Bering is a self-taught programmer that also happens to be a farmer (or a Farmer that also happens to be a self-taught Programmer).  His day-to-day involves developing desktop and web applications to help his family's growing Maple Syrup operation, as well as printing labels for their products, and giving tours of their operation to the interested public."
baseurl: ""
url: "http://balrog30.github.io"
twitter_username: Balrog30
github_username:  Balrog30

# Build settings
markdown: kramdown
permalink: pretty
